#%RAML 0.8
title: Softtek Mule Demo
version: 1.0
baseUri: http://softtek-mule-demo-app.cloudhub.io/api


/contacts:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [{"first_name": "Jaime", "last_name": "Garcia", "email": "jgarcia@stk.com", "telephone": "555666777", "id": "1234" }]
  post:
    body:
      application/json:
        example: |
          {"first_name": "Jaime", "last_name": "Garcia", "email": "jgarcia@stk.com", "telephone": "555666777", "id": "1234" }

    responses:
      201:
        body:
          application/json:
            example: |
              {"message": "Contact added"}
              